version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php-production/dockerfile
    ports:
      - "80:80"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pw
    volumes:
      - "./data/db:/var/lib/postgresql/data"