version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/dockerfile
    volumes:
      - "./:/app/"
    ports:
      - "4321:80"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pw
    volumes:
      - "./data/db:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
