version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/dockerfile
    volumes:
      - "./:/app/"
    ports:
      - "4321:80"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pw